name: CI

on: [push]

jobs:
  check-code:
    name: Check code quality
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Check code quality
        run: make check
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [ '3.5', '3.6', '3.7' ]
    name: Test on Python ${{ matrix.python }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install dev-requirements.txt
      - name: Run tests
        run: nosetests --verbose --with-coverage --cover-package kb_python
